export default {
   async linhaganho(bet: number) {
      const numeroAleatorio: number = Math.floor(Math.random() * 2) + 1
      console.log("linha de ganho " + numeroAleatorio)

      const jsons: any = {
         [1]: {
            [0]: {
               wp: { "8": [2, 7, 11], "17": [3, 6, 11] },
               wp3x5: { "8": [1, 5, 8], "17": [2, 4, 8] },
               wpl: [2, 7, 11, 3, 6],
               ptbr: [2, 7, 3, 6],
               lw: { "8": 1.2, "17": 0.75 },
               lwm: null,
               rl3x5: [7, 4, 6, 3, 6, 4, 8, 5, 0, 2, 7, 8, 7, 8, 7],
               swl: [[11, 2]],
               swlb: [[11, 2]],
               nswl: [[11, 2]],
               rswl: [],
               rs: null,
               fs: null,
               gml: [1, 2, 3, 5],
               cwc: 1,
               fstc: null,
               rwsp: { "8": 8.0, "17": 5.0 },
               rl: [8, 7, 4, 6, 3, 3, 6, 4, 8, 8, 5, 0, 7, 2, 7, 8, 6, 7, 8, 7],
               st: 1,
               nst: 4,
            },
            [1]: {
               wp: null,
               wp3x5: null,
               wpl: null,
               ptbr: null,
               lw: null,
               lwm: null,
               rl3x5: [6, 8, 7, 7, 3, 3, 8, 5, 0, 2, 7, 8, 7, 8, 7],
               swl: [[11, 2]],
               swlb: [[11, 2]],
               nswl: null,
               rswl: null,
               rs: { rns: [[5, 6], [7, 7], null, null, null] },
               fs: null,
               gml: [1, 2, 3, 5],
               cwc: 0,
               fstc: { "4": 1 },
               rwsp: null,
               rl: [5, 6, 8, 7, 7, 7, 3, 3, 8, 8, 5, 0, 7, 2, 7, 8, 6, 7, 8, 7],
               st: 4,
               nst: 1,
            },
         },
         [2]: {
            [0]: {
               wp: { "3": [3, 7, 11], "10": [1, 6, 10] },
               wp3x5: { "3": [2, 5, 8], "10": [0, 4, 7] },
               wpl: [3, 7, 11, 1, 6, 10],
               ptbr: [3, 7, 11, 1, 6, 10],
               lw: { "3": 3.0, "10": 3.0 },
               lwm: null,
               rl3x5: [5, 7, 6, 7, 5, 6, 8, 5, 6, 7, 4, 5, 7, 6, 8],
               swl: null,
               swlb: null,
               nswl: null,
               rswl: [],
               rs: null,
               fs: null,
               gml: [1, 2, 3, 5],
               cwc: 1,
               fstc: null,
               rwsp: { "3": 5.0, "10": 5.0 },
               rl: [7, 5, 7, 6, 5, 7, 5, 6, 8, 8, 5, 6, 6, 7, 4, 5, 2, 7, 6, 8],
               st: 1,
               nst: 4,
            },
            [1]: {
               wp: null,
               wp3x5: null,
               wpl: null,
               ptbr: null,
               lw: null,
               lwm: null,
               rl3x5: [2, 7, 7, 8, 5, 7, 2, 8, 8, 7, 4, 5, 7, 6, 8],
               swl: null,
               swlb: null,
               nswl: null,
               rswl: null,
               rs: { rns: [[5, 2], [6, 8], [8, 2], null, null] },
               fs: null,
               gml: [1, 2, 3, 5],
               cwc: 0,
               fstc: { "4": 1 },
               rwsp: null,
               rl: [5, 2, 7, 7, 6, 8, 5, 7, 8, 2, 8, 8, 6, 7, 4, 5, 2, 7, 6, 8],
               st: 4,
               nst: 1,
            }
         },
      }
      return jsons[numeroAleatorio]
   },
}
